# Current Server Profile Setting

server.servlet.context-path= /
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

## Redis
spring.cache.type=redis
spring.cache.redis.time-to-live=3600
spring.cache.redis.host=redis-cluster
spring.cache.redis.port=6379

# MySQL
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=1000
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.datasource.write.jdbc-url=jdbc:mysql://surveydb-router.db.svc.cluster.local:6446/surveydb?useSSL=false&characterEncoding=UTF-8
spring.datasource.write.username=root
spring.datasource.write.password=admin
spring.datasource.write.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.read.jdbc-url=jdbc:mysql://surveydb-router.db.svc.cluster.local:6447/surveydb?useSSL=false&characterEncoding=UTF-8
spring.datasource.read.username=root
spring.datasource.read.password=admin
spring.datasource.read.driver-class-name=com.mysql.cj.jdbc.Driver

## Spring Gateway
gateway.host=gateway-service:8080

# Prometheus
management.server.port=8082
management.endpoints.web.exposure.include=*

# Spring Security
spring.security.user.name=admin
spring.security.user.password=97Swave99!
spring.security.user.roles=ENDPOINT_ADMIN
