## Current Server Profile Setting
server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: survey-analyze
          uri: http://analysis-back-service:8080/
          predicates:
            - Path=/api/analyze/internal/**
            - Method=GET,POST
        - id: survey-analyze
          uri: http://analysis-back-service:8080/
          predicates:
            - Path=/api/analyze/external/**
            - Method=GET,POST
          filters:
            - AuthorizationHeaderFilter

        - id: survey-answer
          uri: http://response-back-service:8080/
          predicates:
            - Path=/api/answer/external/**
            - Method=GET,POST
        - id: survey-answer
          uri: http://response-back-service:8080/
          predicates:
            - Path=/api/answer/internal/**
            - Method=GET,POST

        - id: surveydocument
          uri: http://survey-back-service:8080/
          predicates:
            - Path=/api/document/external/**
            - Method=GET,POST
          filters:
            - AuthorizationHeaderFilter
        - id: surveydocument
          uri: http://survey-back-service:8080/
          predicates:
            - Path=/api/document/internal/**
            - Method=GET,POST

        - id: surveydocument
          uri: http://survey-back-service:8080/
          predicates:
            - Path=/api/document/oauth/**
            - Method=GET,POST

        - id: user
          uri: http://user-back-service:8080/
          predicates:
            - Path=/api/user/external/**
            - Method=GET,POST
        - id: user
          uri: http://user-back-service:8080/
          predicates:
            - Path=/api/user/internal/**
            - Method=GET,POST

        - id: default-route
          uri: forward:/default-response
          predicates:
            - Path=/**
management:
 endpoints:
   web:
     exposure:
       include: refresh, health, beans, httptrace
token:
  expiration-time: 86400000 # 하루짜리 토큰 생성
  secret: changhwan2022changhwanchanghwan2022changhwanchanghwan2022changhwanchanghwan2022changhwanchanghwan2022changhwan
logging:
  level:
    org.springframework.cloud.gateway: INFO
    # reactor.netty: trace
---
